[build]
  publish = "dist/public"

[[redirects]]
  from = "/api/frenet/*"
  to = "https://api.frenet.com.br/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
