[build]
  publish = "dist/public"
  functions = "netlify/functions"
  command = "pnpm run build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions"]

[dev]
  targetPort = 5173
  port = 8888
  autoLaunch = false



[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
